language: node_js
cache: yarn
before_deploy:
  - openssl aes-256-cbc -K $encrypted_107fb8efbfdf_key -iv $encrypted_107fb8efbfdf_iv -in github_deploy_keu.enc -out github_deploy_keu -d
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
script:
  - yarn build
deploy:
  deploy_key: github_deploy_keu
  provider: script
  script: yarn run deploy
  cleanup: false
  on:
    branch: master
