language: node_js
cache: yarn
env:
  secure: "oGpfI1dJx0aZr87VPDIT0dRe1zcAflYvjRR0erOQAGqXoWpeF1nm1dNGwZy+Np7bfmgTLN3cYyk336w4oF/YZL8Smm2xCJZdiERxGWDFbqL6ykVRZj/kRreASlnXYtSs/Ja6eJiwOypmXEMT0ZZp7hlMdl3hnx7LDMdTOOmhE4epdz5xU8QEHvG4l/nCgtuKr3dHxON+4JS5XrAIgpWehyUGUoijL9cAZx2H1yYbGqKdRc2of0SSYt0Vo+WSgfblEdujoRZDsXIreVffihESQtm/TC/smZo7oEfJCV9hR9tAkyoQac7YWn1aot5jd6bdc0sJPEQ1bIJFpuDgSyXQhchm2Rj+aLvVcV5vrZ9cS8l3f+lke4Lc+D27kb9MhcKO8biTAoTTNf/Rf1XhpIOHyQXvqIFJtWxCDWXFlnGG7QflfJPu7fVLH3m6viWeFVYW5JJYjG83Mo4zNV7n+F6gRCD0qYAu88DcinOh99V4tiTWzpZ862DH/oi9aj79egkJyv75NzuNIOK03Cz7YEjKtVnRQwdFACxzTpmaqAkVIok4djeuBcO6hWjY+/Q/2apD8EOqYrHEtVQfHiH052Jqj6ayxFapBJGMqXMUy1JXJZm4Epgc8KQfkc9D6pkWpgrsKHEF1PDJ8PLy+ZrdB1ftfulZgN+2Vyd0Gve0QGB3pso="
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
script:
  - yarn build
after_success:
  declare -r SSH_FILE="$(mktemp -u $HOME/.ssh/XXXXX)"

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Decrypt the file containing the private key
  # (Note: this is the same as what is generated by the Travis CLI at step 2.5)

  openssl aes-256-cbc \
  -K $encrypted_XXXXXXXXXXXX_key \
  -iv $encrypted_XXXXXXXXXXXX_iv \
  -in ".travis/github_deploy_key.enc" \
  -out "$SSH_FILE" -d

  # - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

  # Enable SSH authentication

  chmod 600 "$SSH_FILE" \
  && printf "%s\n" \
  "Host github.com" \
  "  IdentityFile $SSH_FILE" \
  "  LogLevel ERROR" >> ~/.ssh/config
deploy:
  provider: script
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master
