language: node_js
cache: yarn
before_script:
  - npm install -g gatsby-cli
node_js:
  - "12"
script:
  - yarn build
deploy:
  deploy_key: github_deploy_keu
  provider: script
  script: yarn run deploy
  skip_cleanup: true
  on:
    branch: master
