# Sidebar navigation

- label: 'General'
  items:
    - label: 'Introduction'
      link: '/'
    - label: 'Discord'
      link: 'https://discord.gg/mUujvHD'
    - label: 'Github'
      link: 'https://github.com/anvilpowered/'
    - label: 'TeamCity'
      link: 'http://ci.anvilpowered.org'
- label: 'Anvil'
  items:
    - label: 'Commands'
      link: '/anvil/commands'
    - label: 'Configuration'
      link: '/anvil/configuration'
    - label: 'Developers'
      link: '/anvil/developers'
    - label: 'Releases'
      link: 'https://github.com/anvilpowered/anvil/releases'
- label: 'Catalyst'
  items:
    - label: 'About'
      link: '/catalyst/about'
    - label: 'Commands'
      link: '/catalyst/commands'
    - label: 'Configuration'
      link: '/catalyst/configuration'
    - label: 'Releases'
      link: 'https://github.com/anvilpowered/catalyst/releases'
- label: 'DataSync'
  items:
    - label: 'About'
      link: '/datasync/about'
    - label: 'Commands'
      link: '/datasync/commands'
    - label: 'Configuration'
      link: '/datasync/configuration'
    - label: 'Releases'
      link: 'https://github.com/anvilpowered/datasync/releases'
- label: 'OnTime'
  items:
    - label: 'About'
      link: '/ontime/about'
    - label: 'Commands'
      link: '/ontime/commands'
    - label: 'Configuration'
      link: '/ontime/configuration'
    - label: 'Releases'
      link: 'https://github.com/anvilpowered/ontime/releases'
